/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-21 15:27:30 UTC)
 * on 2013-08-26 at 10:23:59 UTC 
 * Modify at your own risk.
 */

package com.jalbasri.squawk.deviceinfoendpoint.model;

/**
 * Model definition for Place.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Place extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer accessLevel;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.util.List<GeoLocation>> boundingBoxCoordinates;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String boundingBoxType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Place> containedWithIn;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String country;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String countryCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fullName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.util.List<GeoLocation>> geometryCoordinates;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String geometryType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String placeType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private RateLimitStatus rateLimitStatus;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String streetAddress;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String url;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getAccessLevel() {
    return accessLevel;
  }

  /**
   * @param accessLevel accessLevel or {@code null} for none
   */
  public Place setAccessLevel(java.lang.Integer accessLevel) {
    this.accessLevel = accessLevel;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.util.List<GeoLocation>> getBoundingBoxCoordinates() {
    return boundingBoxCoordinates;
  }

  /**
   * @param boundingBoxCoordinates boundingBoxCoordinates or {@code null} for none
   */
  public Place setBoundingBoxCoordinates(java.util.List<java.util.List<GeoLocation>> boundingBoxCoordinates) {
    this.boundingBoxCoordinates = boundingBoxCoordinates;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBoundingBoxType() {
    return boundingBoxType;
  }

  /**
   * @param boundingBoxType boundingBoxType or {@code null} for none
   */
  public Place setBoundingBoxType(java.lang.String boundingBoxType) {
    this.boundingBoxType = boundingBoxType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Place> getContainedWithIn() {
    return containedWithIn;
  }

  /**
   * @param containedWithIn containedWithIn or {@code null} for none
   */
  public Place setContainedWithIn(java.util.List<Place> containedWithIn) {
    this.containedWithIn = containedWithIn;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCountry() {
    return country;
  }

  /**
   * @param country country or {@code null} for none
   */
  public Place setCountry(java.lang.String country) {
    this.country = country;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCountryCode() {
    return countryCode;
  }

  /**
   * @param countryCode countryCode or {@code null} for none
   */
  public Place setCountryCode(java.lang.String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFullName() {
    return fullName;
  }

  /**
   * @param fullName fullName or {@code null} for none
   */
  public Place setFullName(java.lang.String fullName) {
    this.fullName = fullName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.util.List<GeoLocation>> getGeometryCoordinates() {
    return geometryCoordinates;
  }

  /**
   * @param geometryCoordinates geometryCoordinates or {@code null} for none
   */
  public Place setGeometryCoordinates(java.util.List<java.util.List<GeoLocation>> geometryCoordinates) {
    this.geometryCoordinates = geometryCoordinates;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGeometryType() {
    return geometryType;
  }

  /**
   * @param geometryType geometryType or {@code null} for none
   */
  public Place setGeometryType(java.lang.String geometryType) {
    this.geometryType = geometryType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Place setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Place setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPlaceType() {
    return placeType;
  }

  /**
   * @param placeType placeType or {@code null} for none
   */
  public Place setPlaceType(java.lang.String placeType) {
    this.placeType = placeType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public RateLimitStatus getRateLimitStatus() {
    return rateLimitStatus;
  }

  /**
   * @param rateLimitStatus rateLimitStatus or {@code null} for none
   */
  public Place setRateLimitStatus(RateLimitStatus rateLimitStatus) {
    this.rateLimitStatus = rateLimitStatus;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStreetAddress() {
    return streetAddress;
  }

  /**
   * @param streetAddress streetAddress or {@code null} for none
   */
  public Place setStreetAddress(java.lang.String streetAddress) {
    this.streetAddress = streetAddress;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUrl() {
    return url;
  }

  /**
   * @param url url or {@code null} for none
   */
  public Place setUrl(java.lang.String url) {
    this.url = url;
    return this;
  }

  @Override
  public Place set(String fieldName, Object value) {
    return (Place) super.set(fieldName, value);
  }

  @Override
  public Place clone() {
    return (Place) super.clone();
  }

}
