/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-21 15:27:30 UTC)
 * on 2013-08-23 at 05:49:44 UTC 
 * Modify at your own risk.
 */

package com.jalbasri.squawk.deviceinfoendpoint.model;

/**
 * Model definition for MapRegion.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MapRegion extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double northEastLatitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double northEastLongitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double southWestLatitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double southWestLongitude;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getNorthEastLatitude() {
    return northEastLatitude;
  }

  /**
   * @param northEastLatitude northEastLatitude or {@code null} for none
   */
  public MapRegion setNorthEastLatitude(java.lang.Double northEastLatitude) {
    this.northEastLatitude = northEastLatitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getNorthEastLongitude() {
    return northEastLongitude;
  }

  /**
   * @param northEastLongitude northEastLongitude or {@code null} for none
   */
  public MapRegion setNorthEastLongitude(java.lang.Double northEastLongitude) {
    this.northEastLongitude = northEastLongitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getSouthWestLatitude() {
    return southWestLatitude;
  }

  /**
   * @param southWestLatitude southWestLatitude or {@code null} for none
   */
  public MapRegion setSouthWestLatitude(java.lang.Double southWestLatitude) {
    this.southWestLatitude = southWestLatitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getSouthWestLongitude() {
    return southWestLongitude;
  }

  /**
   * @param southWestLongitude southWestLongitude or {@code null} for none
   */
  public MapRegion setSouthWestLongitude(java.lang.Double southWestLongitude) {
    this.southWestLongitude = southWestLongitude;
    return this;
  }

  @Override
  public MapRegion set(String fieldName, Object value) {
    return (MapRegion) super.set(fieldName, value);
  }

  @Override
  public MapRegion clone() {
    return (MapRegion) super.clone();
  }

}
