/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-21 15:27:30 UTC)
 * on 2013-08-26 at 10:23:59 UTC 
 * Modify at your own risk.
 */

package com.jalbasri.squawk.deviceinfoendpoint.model;

/**
 * Model definition for User.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class User extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer accessLevel;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String biggerProfileImageURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String biggerProfileImageURLHttps;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean contributorsEnabled;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime createdAt;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<URLEntity> descriptionURLEntities;

  static {
    // hack to force ProGuard to consider URLEntity used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(URLEntity.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer favouritesCount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean followRequestSent;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer followersCount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer friendsCount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean geoEnabled;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String lang;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer listedCount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String location;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String miniProfileImageURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String miniProfileImageURLHttps;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String originalProfileImageURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String originalProfileImageURLHttps;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileBackgroundColor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileBackgroundImageURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileBackgroundImageUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileBackgroundImageUrlHttps;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean profileBackgroundTiled;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileBannerIPadRetinaURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileBannerIPadURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileBannerMobileRetinaURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileBannerMobileURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileBannerRetinaURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileBannerURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileImageURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileImageURLHttps;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private URL profileImageUrlHttps;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileLinkColor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileSidebarBorderColor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileSidebarFillColor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileTextColor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean profileUseBackgroundImage;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("protected")
  private java.lang.Boolean deviceinfoendpointProtected;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private RateLimitStatus rateLimitStatus;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String screenName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean showAllInlineMedia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Status status;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer statusesCount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String timeZone;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean translator;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String url;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private URLEntity urlentity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer utcOffset;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean verified;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getAccessLevel() {
    return accessLevel;
  }

  /**
   * @param accessLevel accessLevel or {@code null} for none
   */
  public User setAccessLevel(java.lang.Integer accessLevel) {
    this.accessLevel = accessLevel;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBiggerProfileImageURL() {
    return biggerProfileImageURL;
  }

  /**
   * @param biggerProfileImageURL biggerProfileImageURL or {@code null} for none
   */
  public User setBiggerProfileImageURL(java.lang.String biggerProfileImageURL) {
    this.biggerProfileImageURL = biggerProfileImageURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBiggerProfileImageURLHttps() {
    return biggerProfileImageURLHttps;
  }

  /**
   * @param biggerProfileImageURLHttps biggerProfileImageURLHttps or {@code null} for none
   */
  public User setBiggerProfileImageURLHttps(java.lang.String biggerProfileImageURLHttps) {
    this.biggerProfileImageURLHttps = biggerProfileImageURLHttps;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getContributorsEnabled() {
    return contributorsEnabled;
  }

  /**
   * @param contributorsEnabled contributorsEnabled or {@code null} for none
   */
  public User setContributorsEnabled(java.lang.Boolean contributorsEnabled) {
    this.contributorsEnabled = contributorsEnabled;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getCreatedAt() {
    return createdAt;
  }

  /**
   * @param createdAt createdAt or {@code null} for none
   */
  public User setCreatedAt(com.google.api.client.util.DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public User setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<URLEntity> getDescriptionURLEntities() {
    return descriptionURLEntities;
  }

  /**
   * @param descriptionURLEntities descriptionURLEntities or {@code null} for none
   */
  public User setDescriptionURLEntities(java.util.List<URLEntity> descriptionURLEntities) {
    this.descriptionURLEntities = descriptionURLEntities;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getFavouritesCount() {
    return favouritesCount;
  }

  /**
   * @param favouritesCount favouritesCount or {@code null} for none
   */
  public User setFavouritesCount(java.lang.Integer favouritesCount) {
    this.favouritesCount = favouritesCount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getFollowRequestSent() {
    return followRequestSent;
  }

  /**
   * @param followRequestSent followRequestSent or {@code null} for none
   */
  public User setFollowRequestSent(java.lang.Boolean followRequestSent) {
    this.followRequestSent = followRequestSent;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getFollowersCount() {
    return followersCount;
  }

  /**
   * @param followersCount followersCount or {@code null} for none
   */
  public User setFollowersCount(java.lang.Integer followersCount) {
    this.followersCount = followersCount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getFriendsCount() {
    return friendsCount;
  }

  /**
   * @param friendsCount friendsCount or {@code null} for none
   */
  public User setFriendsCount(java.lang.Integer friendsCount) {
    this.friendsCount = friendsCount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getGeoEnabled() {
    return geoEnabled;
  }

  /**
   * @param geoEnabled geoEnabled or {@code null} for none
   */
  public User setGeoEnabled(java.lang.Boolean geoEnabled) {
    this.geoEnabled = geoEnabled;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public User setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLang() {
    return lang;
  }

  /**
   * @param lang lang or {@code null} for none
   */
  public User setLang(java.lang.String lang) {
    this.lang = lang;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getListedCount() {
    return listedCount;
  }

  /**
   * @param listedCount listedCount or {@code null} for none
   */
  public User setListedCount(java.lang.Integer listedCount) {
    this.listedCount = listedCount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLocation() {
    return location;
  }

  /**
   * @param location location or {@code null} for none
   */
  public User setLocation(java.lang.String location) {
    this.location = location;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMiniProfileImageURL() {
    return miniProfileImageURL;
  }

  /**
   * @param miniProfileImageURL miniProfileImageURL or {@code null} for none
   */
  public User setMiniProfileImageURL(java.lang.String miniProfileImageURL) {
    this.miniProfileImageURL = miniProfileImageURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMiniProfileImageURLHttps() {
    return miniProfileImageURLHttps;
  }

  /**
   * @param miniProfileImageURLHttps miniProfileImageURLHttps or {@code null} for none
   */
  public User setMiniProfileImageURLHttps(java.lang.String miniProfileImageURLHttps) {
    this.miniProfileImageURLHttps = miniProfileImageURLHttps;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public User setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOriginalProfileImageURL() {
    return originalProfileImageURL;
  }

  /**
   * @param originalProfileImageURL originalProfileImageURL or {@code null} for none
   */
  public User setOriginalProfileImageURL(java.lang.String originalProfileImageURL) {
    this.originalProfileImageURL = originalProfileImageURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOriginalProfileImageURLHttps() {
    return originalProfileImageURLHttps;
  }

  /**
   * @param originalProfileImageURLHttps originalProfileImageURLHttps or {@code null} for none
   */
  public User setOriginalProfileImageURLHttps(java.lang.String originalProfileImageURLHttps) {
    this.originalProfileImageURLHttps = originalProfileImageURLHttps;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileBackgroundColor() {
    return profileBackgroundColor;
  }

  /**
   * @param profileBackgroundColor profileBackgroundColor or {@code null} for none
   */
  public User setProfileBackgroundColor(java.lang.String profileBackgroundColor) {
    this.profileBackgroundColor = profileBackgroundColor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileBackgroundImageURL() {
    return profileBackgroundImageURL;
  }

  /**
   * @param profileBackgroundImageURL profileBackgroundImageURL or {@code null} for none
   */
  public User setProfileBackgroundImageURL(java.lang.String profileBackgroundImageURL) {
    this.profileBackgroundImageURL = profileBackgroundImageURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileBackgroundImageUrl() {
    return profileBackgroundImageUrl;
  }

  /**
   * @param profileBackgroundImageUrl profileBackgroundImageUrl or {@code null} for none
   */
  public User setProfileBackgroundImageUrl(java.lang.String profileBackgroundImageUrl) {
    this.profileBackgroundImageUrl = profileBackgroundImageUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileBackgroundImageUrlHttps() {
    return profileBackgroundImageUrlHttps;
  }

  /**
   * @param profileBackgroundImageUrlHttps profileBackgroundImageUrlHttps or {@code null} for none
   */
  public User setProfileBackgroundImageUrlHttps(java.lang.String profileBackgroundImageUrlHttps) {
    this.profileBackgroundImageUrlHttps = profileBackgroundImageUrlHttps;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getProfileBackgroundTiled() {
    return profileBackgroundTiled;
  }

  /**
   * @param profileBackgroundTiled profileBackgroundTiled or {@code null} for none
   */
  public User setProfileBackgroundTiled(java.lang.Boolean profileBackgroundTiled) {
    this.profileBackgroundTiled = profileBackgroundTiled;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileBannerIPadRetinaURL() {
    return profileBannerIPadRetinaURL;
  }

  /**
   * @param profileBannerIPadRetinaURL profileBannerIPadRetinaURL or {@code null} for none
   */
  public User setProfileBannerIPadRetinaURL(java.lang.String profileBannerIPadRetinaURL) {
    this.profileBannerIPadRetinaURL = profileBannerIPadRetinaURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileBannerIPadURL() {
    return profileBannerIPadURL;
  }

  /**
   * @param profileBannerIPadURL profileBannerIPadURL or {@code null} for none
   */
  public User setProfileBannerIPadURL(java.lang.String profileBannerIPadURL) {
    this.profileBannerIPadURL = profileBannerIPadURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileBannerMobileRetinaURL() {
    return profileBannerMobileRetinaURL;
  }

  /**
   * @param profileBannerMobileRetinaURL profileBannerMobileRetinaURL or {@code null} for none
   */
  public User setProfileBannerMobileRetinaURL(java.lang.String profileBannerMobileRetinaURL) {
    this.profileBannerMobileRetinaURL = profileBannerMobileRetinaURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileBannerMobileURL() {
    return profileBannerMobileURL;
  }

  /**
   * @param profileBannerMobileURL profileBannerMobileURL or {@code null} for none
   */
  public User setProfileBannerMobileURL(java.lang.String profileBannerMobileURL) {
    this.profileBannerMobileURL = profileBannerMobileURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileBannerRetinaURL() {
    return profileBannerRetinaURL;
  }

  /**
   * @param profileBannerRetinaURL profileBannerRetinaURL or {@code null} for none
   */
  public User setProfileBannerRetinaURL(java.lang.String profileBannerRetinaURL) {
    this.profileBannerRetinaURL = profileBannerRetinaURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileBannerURL() {
    return profileBannerURL;
  }

  /**
   * @param profileBannerURL profileBannerURL or {@code null} for none
   */
  public User setProfileBannerURL(java.lang.String profileBannerURL) {
    this.profileBannerURL = profileBannerURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileImageURL() {
    return profileImageURL;
  }

  /**
   * @param profileImageURL profileImageURL or {@code null} for none
   */
  public User setProfileImageURL(java.lang.String profileImageURL) {
    this.profileImageURL = profileImageURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileImageURLHttps() {
    return profileImageURLHttps;
  }

  /**
   * @param profileImageURLHttps profileImageURLHttps or {@code null} for none
   */
  public User setProfileImageURLHttps(java.lang.String profileImageURLHttps) {
    this.profileImageURLHttps = profileImageURLHttps;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public URL getProfileImageUrlHttps() {
    return profileImageUrlHttps;
  }

  /**
   * @param profileImageUrlHttps profileImageUrlHttps or {@code null} for none
   */
  public User setProfileImageUrlHttps(URL profileImageUrlHttps) {
    this.profileImageUrlHttps = profileImageUrlHttps;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileLinkColor() {
    return profileLinkColor;
  }

  /**
   * @param profileLinkColor profileLinkColor or {@code null} for none
   */
  public User setProfileLinkColor(java.lang.String profileLinkColor) {
    this.profileLinkColor = profileLinkColor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileSidebarBorderColor() {
    return profileSidebarBorderColor;
  }

  /**
   * @param profileSidebarBorderColor profileSidebarBorderColor or {@code null} for none
   */
  public User setProfileSidebarBorderColor(java.lang.String profileSidebarBorderColor) {
    this.profileSidebarBorderColor = profileSidebarBorderColor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileSidebarFillColor() {
    return profileSidebarFillColor;
  }

  /**
   * @param profileSidebarFillColor profileSidebarFillColor or {@code null} for none
   */
  public User setProfileSidebarFillColor(java.lang.String profileSidebarFillColor) {
    this.profileSidebarFillColor = profileSidebarFillColor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileTextColor() {
    return profileTextColor;
  }

  /**
   * @param profileTextColor profileTextColor or {@code null} for none
   */
  public User setProfileTextColor(java.lang.String profileTextColor) {
    this.profileTextColor = profileTextColor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getProfileUseBackgroundImage() {
    return profileUseBackgroundImage;
  }

  /**
   * @param profileUseBackgroundImage profileUseBackgroundImage or {@code null} for none
   */
  public User setProfileUseBackgroundImage(java.lang.Boolean profileUseBackgroundImage) {
    this.profileUseBackgroundImage = profileUseBackgroundImage;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getProtected() {
    return deviceinfoendpointProtected;
  }

  /**
   * @param deviceinfoendpointProtected deviceinfoendpointProtected or {@code null} for none
   */
  public User setProtected(java.lang.Boolean deviceinfoendpointProtected) {
    this.deviceinfoendpointProtected = deviceinfoendpointProtected;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public RateLimitStatus getRateLimitStatus() {
    return rateLimitStatus;
  }

  /**
   * @param rateLimitStatus rateLimitStatus or {@code null} for none
   */
  public User setRateLimitStatus(RateLimitStatus rateLimitStatus) {
    this.rateLimitStatus = rateLimitStatus;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getScreenName() {
    return screenName;
  }

  /**
   * @param screenName screenName or {@code null} for none
   */
  public User setScreenName(java.lang.String screenName) {
    this.screenName = screenName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getShowAllInlineMedia() {
    return showAllInlineMedia;
  }

  /**
   * @param showAllInlineMedia showAllInlineMedia or {@code null} for none
   */
  public User setShowAllInlineMedia(java.lang.Boolean showAllInlineMedia) {
    this.showAllInlineMedia = showAllInlineMedia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Status getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public User setStatus(Status status) {
    this.status = status;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getStatusesCount() {
    return statusesCount;
  }

  /**
   * @param statusesCount statusesCount or {@code null} for none
   */
  public User setStatusesCount(java.lang.Integer statusesCount) {
    this.statusesCount = statusesCount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTimeZone() {
    return timeZone;
  }

  /**
   * @param timeZone timeZone or {@code null} for none
   */
  public User setTimeZone(java.lang.String timeZone) {
    this.timeZone = timeZone;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getTranslator() {
    return translator;
  }

  /**
   * @param translator translator or {@code null} for none
   */
  public User setTranslator(java.lang.Boolean translator) {
    this.translator = translator;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUrl() {
    return url;
  }

  /**
   * @param url url or {@code null} for none
   */
  public User setUrl(java.lang.String url) {
    this.url = url;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public URLEntity getUrlentity() {
    return urlentity;
  }

  /**
   * @param urlentity urlentity or {@code null} for none
   */
  public User setUrlentity(URLEntity urlentity) {
    this.urlentity = urlentity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getUtcOffset() {
    return utcOffset;
  }

  /**
   * @param utcOffset utcOffset or {@code null} for none
   */
  public User setUtcOffset(java.lang.Integer utcOffset) {
    this.utcOffset = utcOffset;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getVerified() {
    return verified;
  }

  /**
   * @param verified verified or {@code null} for none
   */
  public User setVerified(java.lang.Boolean verified) {
    this.verified = verified;
    return this;
  }

  @Override
  public User set(String fieldName, Object value) {
    return (User) super.set(fieldName, value);
  }

  @Override
  public User clone() {
    return (User) super.clone();
  }

}
